# Generated by fusen: do not edit by hand

file <- system.file("corrupted_toydatasets.xlsx", package = "annamantsoki")
test_that("multi_import_excel works", {
  expect_type(multi_import_excel(file), type = "list")
})
