# Generated by fusen: do not edit by hand

#' bmi A function to calculate the body mass index 
#' @param mass  the mass of a person in Kg (type = double, numeric)
#' @param height the height of a person in metres (type = double, numeric)
#' @return A vector with the calculated body mass index
#' @export
#'
#' @examples
#' bmi(mass = 80, height = 1.80)
#' library(dplyr)
#' data("data_weight")
#' data_weight %>%
#'   mutate(bmi = bmi(mass = mass, height = height))
bmi <- function(mass = 80, height = 1.80){
 result = mass/(height * height)
 return(result)
}

