# Generated by fusen: do not edit by hand

#' bmi A function to read all available tabs from an excel file 
#' @param file  the name or pathfile of the excel file (type = character)
#' @param ...
#' @return A list of data frames named after the excel tabs
#' @importFrom purrr safely map
#' @importFrom readxl read_excel excel_sheets
#' @export

#' @examples
#' file <- system.file("corrupted_toydatasets.xlsx", package = "annamantsoki")
#' multi_import_excel(file)
#' 
multi_import_excel <- function(file = "inst/corrupted_toydatasets.xlsx"){
  sheets <- excel_sheets(file)
  l <- map(sheets, safe_read_excel, path = file)
  names(l) <- sheets
  return(l)
}

