# Generated by fusen: do not edit by hand

#' bmi A function to read safely an excel file 
#' @param file  the name or pathfile of the excel file (type = character)
#' @param ...
#' @return A data frame or NULL in case of corruption
#' @importFrom purrr safely
#' @importFrom readxl read_excel 
#' @export

safe_read_excel <- safely(read_excel) 

